{% set name = "pgvector" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgvector-{{ version }}.tar.gz
  sha256: 83d3a1c044ff0c2f1e95d13dfb625beb0b65506cfec0941bfe81fd0ad44f4003

build:
  skip: true # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - pgvector
    - pgvector.sqlalchemy
    - pgvector.utils
    # Requires 'psycopg' package which is not available for now
    # - pgvector.psycopg
    - pgvector.psycopg2
    - pgvector.pg8000
    - pgvector.peewee
    - pgvector.asyncpg
    - pgvector.django
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - sqlalchemy
    - peewee
    - django
    - psycopg2
    - sqlmodel
    - asyncpg
    - pg8000
    - scipy

about:
  home: https://github.com/pgvector/pgvector
  summary: Open-source vector similarity search for Postgres.
  description: Open-source vector similarity search for Postgres.
  license: PostgreSQL
  license_file: LICENSE.txt
  license_family: other
  doc_url: https://github.com/pgvector/pgvector
  dev_url: https://github.com/pgvector/pgvector

extra:
  recipe-maintainers:
    - mmcauliffe
