{% set name = "pgvector-python" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pgvector/pgvector-{{ version }}.tar.gz
  sha256: 07a9dcf735696879406983afc6eba9a787cef7c0cf6c367ca1a5779f036dee74

build:
  skip: true # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - pgvector
    - pgvector.sqlalchemy
    - pgvector.utils
    # Requires 'psycopg' package which is not available for now
    # - pgvector.psycopg
    - pgvector.psycopg2
    - pgvector.pg8000
    - pgvector.peewee
    - pgvector.asyncpg
    - pgvector.django
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('pgvector')=='{{ version }}')"
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - sqlalchemy
    - peewee
    - django
    - psycopg2
    - sqlmodel
    - asyncpg
    - pg8000
    - scipy

about:
  home: https://github.com/pgvector/pgvector-python
  summary: pgvector support for Python
  description: |
    pgvector support for Python.
    Great for online recommendations.
    Supports Django, SQLAlchemy, Psycopg 3, Psycopg 2, asyncpg, pg8000, and Peewee.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  doc_url: https://pypi.org/project/pgvector/
  dev_url: https://github.com/pgvector/pgvector-python

extra:
  recipe-maintainers:
    - mmcauliffe
